runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: Assignment/index.html
  upload: Assignment/index.html

- url: /(.*)
  static_files: Assignment/\1
  upload: Assignment/(.*)
